export const ACCENT_COLOR = "#FF4081"
export const DARK_PRIMARY_COLOR = "#7B1FA2"
export const LIGHT_PRIMARY_COLOR = "#E1BEE7"
export const PRIMARY_TEXT = "#212121"
export const PRIMARY_COLOR = "#9C27B0"
export const TEXT_ICONS = "#FFFFFF"
export const DIVIDER_COLOR = "#BDBDBD"
